Update Dockerfile and GitHub Actions workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,25 +12,35 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Build your project
-        run: |
-          make generate
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-      - name: Copy file to remote server
+      - name: Build and run domain-list-community with Docker Compose
+        run: |
+          docker-compose up --build --abort-on-container-exit
+          ls -lh output/
+
+      - name: Check output file permissions
+        run: |
+          ls -l output/
+          file output/custom.dat
+          head output/custom.dat || echo "cannot read"
+
+      - name: Upload compiled custom.dat to server
         uses: appleboy/scp-action@v0.1.4
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
-          source: "custom.dat"
+          source: "output/custom.dat"
           target: "/usr/local/x-ui/bin/"
 
-      - name: Set permissions on server
-        uses: appleboy/ssh-action@v1.0.0
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
-          script: |
-            sudo chown ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_UID }} /usr/local/x-ui/bin/custom.dat
-            sudo chmod +x /usr/local/x-ui/bin/custom.dat
+      # - name: Set permissions on server
+      #   uses: appleboy/ssh-action@v1.0.0
+      #   with:
+      #     host: ${{ secrets.SERVER_HOST }}
+      #     username: ${{ secrets.SERVER_USER }}
+      #     key: ${{ secrets.SERVER_SSH_KEY }}
+      #     script: |
+      #       sudo chown ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_UID }} /usr/local/x-ui/bin/custom.dat
+      #       sudo chmod +x /usr/local/x-ui/bin/custom.dat
